FROM jupyter/minimal-notebook

ENV http_proxy=http://172.27.229.197:8090 \
    https_proxy=http://172.27.229.197:8090

USER root

# Install `libaio` (required for connection to Oracle DB with python)
# and `alien` (required to install RPM packages)
RUN apt update \
&& apt install -y alien libaio1 \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# Download and install Oracle Instant Client
RUN wget \
https://download.oracle.com/otn_software/linux/instantclient/\
19800/oracle-instantclient19.8-basic-19.8.0.0.0-1.x86_64.rpm \
&& alien --scripts oracle-instantclient19.8-basic-19.8.0.0.0-1.x86_64.rpm \
&& dpkg -i oracle-instantclient19.8-basic_19.8.0.0.0-2_amd64.deb \
&& rm oracle-instantclient19.8-basic_19.8.0.0.0-2_amd64.rpm

USER $NB_UID

# Configure Jupyter Notebook to run on DAM SI Monitorfish virtual machine
COPY dam-si-jupyter-config.py /home/jovyan/.jupyter/jupyter_notebook_config.py
