package fr.gouv.cnsp.monitorfish.infrastructure.api.contract

import com.fasterxml.jackson.annotation.JsonInclude
import com.neovisionaries.i18n.CountryCode
import java.time.ZonedDateTime

@JsonInclude(JsonInclude.Include.NON_NULL)
data class MissionActionInfractionDataOutput(
    val infractionType: InfractionType,
    // This field is used to control the Threat CheckTreePicker
    val threats: List<ThreatHierarchyDataOutput>? = null,
    val natinf: Int? = null,
    val natinfDescription: String? = null,
    val threat: String? = null,
    val threatCharacterization: String? = null,
    val comments: String? = null,
)

data class MissionActionDataOutput(
    val id: Int? = null,
    val vesselId: Int? = null,
    val vesselName: String? = null,
    val internalReferenceNumber: String? = null,
    val externalReferenceNumber: String? = null,
    val ircs: String? = null,
    val flagState: CountryCode,
    val districtCode: String? = null,
    val faoAreas: List<String> = listOf(),
    val flightGoals: List<FlightGoal> = listOf(),
    val missionId: Int,
    val actionType: MissionActionType,
    val actionDatetimeUtc: ZonedDateTime,
    val actionEndDatetimeUtc: ZonedDateTime? = null,
    val emitsVms: ControlCheck? = null,
    val emitsAis: ControlCheck? = null,
    val vmsEmissionControlBeforeArrival: ControlCheck? = null,
    val portEntranceAndLandingAuthorized: ControlCheck? = null,
    val logbookOpenedPriorToControl: ControlCheck? = null,
    val logbookMatchesActivity: ControlCheck? = null,
    val licencesMatchActivity: ControlCheck? = null,
    val speciesWeightControlled: ControlCheck? = null,
    val speciesSizeControlled: ControlCheck? = null,
    val separateStowageOfPreservedSpecies: ControlCheck? = null,
    val propulsionEnginePowerControl: ControlCheck? = null,
    val gangwayPresentAndCompliant: ControlCheck? = null,
    val europeanFishingLicenceValid: ControlCheck? = null,
    val stowagePlanPresent: ControlCheck? = null,
    val onboardWeighingPermit: ControlCheck? = null,
    val weighingCertificateAndSystemsValid: ControlCheck? = null,
    val underSizedSeparateStowage: ControlCheck? = null,
    val underSizedSeparateRecording: ControlCheck? = null,
    val weightControlMethod: WeightControlMethod? = null,
    val approvedWeighingOperatorInformation: ControlCheck? = null,
    val holdControlledAfterUnloading: ControlCheck? = null,
    val weighingOperationsMonitoredByInspectors: ControlCheck? = null,
    val licencesAndLogbookObservations: String? = null,
    val infractions: List<MissionActionInfractionDataOutput> = listOf(),
    val speciesObservations: String? = null,
    val seizureAndDiversion: Boolean? = null,
    val numberOfVesselsFlownOver: Int? = null,
    val unitWithoutOmegaGauge: Boolean? = null,
    val controlQualityComments: String? = null,
    val segments: List<MissionActionFleetSegmentDataOutput> = listOf(),
    val facade: String? = null,
    val longitude: Double? = null,
    val latitude: Double? = null,
    val portLocode: String? = null,
    val portName: String? = null,
    val seizureAndDiversionComments: String? = null,
    val otherComments: String? = null,
    val gearOnboard: List<GearControlDataOutput> = listOf(),
    val speciesOnboard: List<SpeciesOnboardControlDataOutput> = listOf(),
    val discardedSpecies: List<DiscardedSpeciesControlDataOutput> = listOf(),
    val vesselGroups: List<MissionActionVesselGroupDataOutput> = listOf(),
    val tripReportings: List<MissionActionReportingDataOutput> = listOf(),
    val controlUnits: List<MissionActionControlUnitDataOutput> = listOf(),
    val userTrigram: String,
    val isPrioritized: Boolean = false,
    val hasSomeGearsSeized: Boolean,
    val hasSomeSpeciesSeized: Boolean,
    val speciesQuantitySeized: Int? = null,
    val completedBy: String? = null,
    val completion: Completion,
    val isFromPoseidon: Boolean,
    val isLastHaul: Boolean,
    val isAdministrativeControl: Boolean? = null,
    val isComplianceWithWaterRegulationsControl: Boolean? = null,
    val isSafetyEquipmentAndStandardsComplianceControl: Boolean? = null,
    val isSeafarersControl: Boolean? = null,
    val isINNControl: Boolean = false,
    val isUnitBoarded: Boolean? = null,
    val isEISR: Boolean? = null,
    val observationsByUnit: String? = null,
)
