import { MissionAction } from '@features/Mission/missionAction.types'

import MissionActionType = MissionAction.MissionActionType
import CompletionStatus = MissionAction.CompletionStatus

export const dummyAction = {
  actionDatetimeUtc: '2023-12-08T08:27:00Z',
  actionEndDatetimeUtc: undefined,
  actionType: MissionActionType.SEA_CONTROL,
  completedBy: undefined,
  completion: CompletionStatus.COMPLETED,
  controlQualityComments: undefined,
  controlUnits: [],
  districtCode: 'AY',
  emitsAis: undefined,
  emitsVms: undefined,
  externalReferenceNumber: 'DONTSINK',
  facade: 'NAMO',
  faoAreas: ['27.8.b', '27.8.c'],
  fishingLicencesMatchActivity: undefined,
  flagState: 'FR',
  flightGoals: [],
  gearOnboard: [
    {
      averageWireThickness: undefined,
      comments: undefined,
      controlledMesh: undefined,
      declaredMesh: 70.0,
      gearCode: 'OTB',
      gearMarkingIsCompliant: undefined,
      gearName: 'Chaluts de fond à panneaux',
      gearWasControlled: undefined,
      hasUncontrolledMesh: false,
      wireType: undefined
    }
  ],
  hasSomeGearsSeized: false,
  hasSomeSpeciesSeized: false,
  id: 123456,
  infractions: [],
  internalReferenceNumber: 'FAK000999999',
  ircs: 'CALLME',
  isAdministrativeControl: undefined,
  isComplianceWithWaterRegulationsControl: undefined,
  isFromPoseidon: false,
  isGangwayDeployed: undefined,
  isINNControl: false,
  isLastHaul: false,
  isSafetyEquipmentAndStandardsComplianceControl: undefined,
  isSeafarersControl: undefined,
  isValid: true,
  latitude: 47.648401281163814,
  licencesAndLogbookObservations: undefined,
  licencesMatchActivity: undefined,
  logbookMatchesActivity: undefined,
  longitude: -4.281934312813745,
  missionId: 123,
  numberOfVesselsFlownOver: undefined,
  observationsByUnit: undefined,
  onboardWeighingPermit: undefined,
  otherComments: undefined,
  portLocode: undefined,
  portName: undefined,
  propulsionEnginePowerControl: undefined,
  segments: [{ segment: 'SWW01/02/03', segmentName: 'Bottom trawls' }],
  seizureAndDiversion: false,
  seizureAndDiversionComments: undefined,
  separateStowageOfPreservedSpecies: undefined,
  speciesObservations: undefined,
  speciesOnboard: [
    {
      controlledWeight: undefined,
      declaredWeight: 471.2,
      nbFish: undefined,
      rejectedWeight: undefined,
      speciesCode: 'HKE',
      underSized: false,
      underSizedWeight: undefined
    },
    {
      controlledWeight: undefined,
      declaredWeight: 13.46,
      nbFish: undefined,
      rejectedWeight: undefined,
      speciesCode: 'BLI',
      underSized: false,
      underSizedWeight: undefined
    }
  ],
  speciesQuantitySeized: undefined,
  speciesSizeControlled: undefined,
  speciesWeightControlled: undefined,
  stowagePlanPresent: undefined,
  underSizedSeparateRecording: undefined,
  underSizedSeparateStowage: undefined,
  unitWithoutOmegaGauge: false,
  userTrigram: 'LT',
  vesselId: 1,
  vesselName: 'PHENOMENE',
  vesselTargeted: undefined,
  weighingCertificateAndSystemsValid: undefined
}
