import { ActiveVesselType, VesselIdentifier } from '@features/Vessel/schemas/ActiveVesselSchema'
import { customDayjs } from '@mtes-mct/monitor-ui'

const now = customDayjs()
export const DUMMY_LAST_POSITIONS = [
  {
    activeVesselType: ActiveVesselType.POSITION_ACTIVITY,
    alerts: [],
    beaconMalfunctionId: undefined,
    beaconNumber: undefined,
    coordinates: [],
    course: undefined,
    dateTime: now.subtract(7, 'minutes').toISOString(),
    detectabilityRiskFactor: 0,
    district: undefined,
    districtCode: undefined,
    emissionPeriod: undefined,
    estimatedCurrentLatitude: undefined,
    estimatedCurrentLongitude: undefined,
    externalReferenceNumber: undefined,
    flagState: 'US',
    gearOnboard: [],
    gearsArray: ['gear1'],
    hasAlert: false,
    hasBeaconMalfunction: false,
    hasInfractionSuspicion: false,
    impactRiskFactor: 0,
    internalReferenceNumber: undefined,
    ircs: undefined,
    isAtPort: true,
    isFiltered: 0,
    lastControlDateTime: now.subtract(15, 'months').toISOString(),
    lastControlInfraction: undefined,
    lastLogbookMessageDateTime: now.subtract(7, 'hours').toISOString(),
    lastPositionSentAt: 0,
    latitude: 0,
    length: 15,
    longitude: 0,
    mmsi: undefined,
    positionType: 'VMS',
    probabilityRiskFactor: 0,
    recentGearsArray: [],
    recentSegments: [],
    registryPortLocode: undefined,
    registryPortName: undefined,
    reportings: [],
    riskFactor: 1.5,
    segments: ['segment1'],
    speciesArray: ['specy1'],
    speciesOnboard: [],
    speed: undefined,
    tripNumber: undefined,
    underCharter: undefined,
    vesselFeatureId: 'vessel1',
    vesselGroups: [],
    vesselId: undefined,
    vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
    vesselName: 'UNKNOWN',
    width: undefined
  },
  {
    activeVesselType: ActiveVesselType.POSITION_ACTIVITY,
    alerts: [],
    beaconMalfunctionId: undefined,
    beaconNumber: undefined,
    coordinates: [],
    course: undefined,
    dateTime: now.subtract(2, 'hours').toISOString(),
    detectabilityRiskFactor: 0,
    district: undefined,
    districtCode: 'GV',
    emissionPeriod: undefined,
    estimatedCurrentLatitude: undefined,
    estimatedCurrentLongitude: undefined,
    externalReferenceNumber: undefined,
    flagState: 'FR',
    gearOnboard: [],
    gearsArray: ['gear2'],
    hasAlert: false,
    hasBeaconMalfunction: false,
    hasInfractionSuspicion: false,
    impactRiskFactor: 0,
    internalReferenceNumber: undefined,
    ircs: undefined,
    isAtPort: false,
    isFiltered: 0,
    lastControlDateTime: now.subtract(2, 'days').toISOString(),
    lastControlInfraction: undefined,
    lastLogbookMessageDateTime: undefined,
    lastPositionSentAt: 0,
    latitude: 0,
    length: 8,
    longitude: 0,
    mmsi: undefined,
    positionType: 'VMS',
    probabilityRiskFactor: 0,
    recentGearsArray: [],
    recentSegments: [],
    registryPortLocode: undefined,
    registryPortName: undefined,
    reportings: [],
    riskFactor: 2.5,
    segments: ['segment2'],
    speciesArray: ['specy2'],
    speciesOnboard: [],
    speed: undefined,
    tripNumber: undefined,
    underCharter: undefined,
    vesselFeatureId: 'vessel2',
    vesselGroups: [],
    vesselId: undefined,
    vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
    vesselName: 'PHENOMENE',
    width: undefined
  },
  {
    activeVesselType: ActiveVesselType.POSITION_ACTIVITY,
    alerts: [],
    beaconMalfunctionId: undefined,
    beaconNumber: undefined,
    coordinates: [],
    course: undefined,
    dateTime: now.toISOString(),
    detectabilityRiskFactor: 0,
    district: undefined,
    districtCode: undefined,
    emissionPeriod: undefined,
    estimatedCurrentLatitude: undefined,
    estimatedCurrentLongitude: undefined,
    externalReferenceNumber: undefined,
    flagState: 'UK',
    gearOnboard: [],
    gearsArray: [],
    hasAlert: false,
    hasBeaconMalfunction: false,
    hasInfractionSuspicion: false,
    impactRiskFactor: 0,
    internalReferenceNumber: undefined,
    ircs: undefined,
    isAtPort: false,
    isFiltered: 0,
    lastControlDateTime: now.subtract(2, 'years').toISOString(),
    lastControlInfraction: undefined,
    lastLogbookMessageDateTime: undefined,
    lastPositionSentAt: 0,
    latitude: 0,
    length: 123,
    longitude: 0,
    mmsi: undefined,
    positionType: 'VMS',
    probabilityRiskFactor: 0,
    recentGearsArray: ['gear666'],
    recentSegments: ['segment666'],
    registryPortLocode: undefined,
    registryPortName: undefined,
    reportings: [],
    riskFactor: 0.1,
    segments: [],
    speciesArray: [],
    speciesOnboard: [],
    speed: undefined,
    tripNumber: undefined,
    underCharter: undefined,
    vesselFeatureId: 'vessel3',
    vesselGroups: [],
    vesselId: undefined,
    vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
    vesselName: 'A BOAT',
    width: undefined
  }
]
