import { ActivityOrigin, ActivityType, VesselIdentifier } from '@features/Vessel/schemas/ActiveVesselSchema'
import { Vessel } from '@features/Vessel/Vessel.types'
import { customDayjs } from '@mtes-mct/monitor-ui'

const now = customDayjs()
export const DUMMY_LAST_POSITIONS: Vessel.ActiveVessel[] = [
  {
    activityOrigin: ActivityOrigin.FROM_LOGBOOK,
    activityType: ActivityType.POSITION_BASED,
    alerts: [],
    beaconMalfunctionId: undefined,
    coordinates: [],
    course: undefined,
    dateTime: now.subtract(7, 'minutes').toISOString(),
    detectabilityRiskFactor: 0,
    emitsPositions: false,
    flagState: 'US',
    gearsArray: ['gear1'],
    hasAlert: false,
    hasBeaconMalfunction: false,
    hasCurrentTripInfractionSuspicion: false,
    hasInfractionSuspicion: false,
    impactRiskFactor: 0,
    isAtPort: true,
    isFiltered: 0,
    lastControlAtQuayDateTime: now.subtract(2, 'months').toISOString(),
    lastControlAtSeaDateTime: now.subtract(15, 'months').toISOString(),
    lastLogbookMessageDateTime: now.subtract(7, 'hours').toISOString(),
    lastPositionSentAt: 0,
    latitude: 47.1585,
    length: 15,
    longitude: -6.12355,
    positionType: 'VMS',
    probabilityRiskFactor: 0,
    producerOrganization: 'SA THO',
    riskFactor: 1.5,
    segments: ['segment1'],
    speciesArray: ['specy1'],
    speciesOnboard: [],
    vesselFeatureId: 'vessel1',
    vesselGroups: [],
    vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
    vesselName: 'UNKNOWN'
  },
  {
    activityOrigin: ActivityOrigin.FROM_LOGBOOK,
    activityType: ActivityType.POSITION_BASED,
    alerts: [],
    beaconMalfunctionId: undefined,
    coordinates: [],
    course: undefined,
    dateTime: now.subtract(2, 'hours').toISOString(),
    detectabilityRiskFactor: 0,
    districtCode: 'GV',
    emitsPositions: false,
    flagState: 'FR',
    gearsArray: ['gear2'],
    hasAlert: false,
    hasBeaconMalfunction: false,
    hasCurrentTripInfractionSuspicion: false,
    hasInfractionSuspicion: false,
    impactRiskFactor: 0,
    isAtPort: false,
    isFiltered: 0,
    lastControlAtQuayDateTime: now.subtract(2, 'years').toISOString(),
    lastControlAtSeaDateTime: now.subtract(2, 'days').toISOString(),
    lastPositionSentAt: 0,
    latitude: 0,
    length: 8,
    longitude: 0,
    positionType: 'VMS',
    probabilityRiskFactor: 0,
    riskFactor: 2.5,
    segments: ['segment2'],
    speciesArray: ['specy2'],
    speciesOnboard: [],
    vesselFeatureId: 'vessel2',
    vesselGroups: [],
    vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
    vesselName: 'PHENOMENE'
  },
  {
    activityOrigin: ActivityOrigin.FROM_RECENT_PROFILE,
    activityType: ActivityType.POSITION_BASED,
    alerts: [],
    beaconMalfunctionId: undefined,
    coordinates: [],
    course: undefined,
    dateTime: now.toISOString(),
    detectabilityRiskFactor: 0,
    emitsPositions: true,
    flagState: 'UK',
    gearsArray: [],
    hasAlert: false,
    hasBeaconMalfunction: false,
    hasCurrentTripInfractionSuspicion: false,
    hasInfractionSuspicion: false,
    impactRiskFactor: 0,
    isAtPort: false,
    isFiltered: 0,
    lastControlAtQuayDateTime: now.subtract(20, 'years').toISOString(),
    lastControlAtSeaDateTime: now.subtract(2, 'years').toISOString(),
    lastPositionSentAt: 0,
    latitude: 0,
    length: 123,
    longitude: 0,
    positionType: 'VMS',
    probabilityRiskFactor: 0,
    producerOrganization: 'SA THO',
    riskFactor: 0.1,
    segments: [],
    speciesArray: [],
    speciesOnboard: [],
    vesselFeatureId: 'vessel3',
    vesselGroups: [],
    vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
    vesselName: 'A BOAT'
  }
]

export const DUMMY_LOGBOOK_BASED_VESSEL: Vessel.ActiveVessel = {
  activityOrigin: ActivityOrigin.FROM_RECENT_PROFILE,
  activityType: ActivityType.LOGBOOK_BASED,
  detectabilityRiskFactor: 1.5811,
  district: 'Saint Malo',
  districtCode: 'SM',
  emitsPositions: false,
  externalReferenceNumber: 'SM561631',
  flagState: 'FR',
  gearsArray: [],
  hasCurrentTripInfractionSuspicion: false,
  hasInfractionSuspicion: false,
  id: 158,
  impactRiskFactor: 1.0,
  internalReferenceNumber: 'FRA000561631',
  ircs: 'FJ9112',
  isAtPort: false,
  isFiltered: 0,
  lastControlAtQuayDateTime: '2026-04-09T09:27:00Z',
  lastControlAtSeaDateTime: '2022-10-27T16:28:00Z',
  length: 11.95,
  mmsi: '227319040',
  probabilityRiskFactor: 1.4142,
  producerOrganization: 'HORS OP',
  riskFactor: 1.3952,
  segments: [],
  speciesArray: [],
  speciesOnboard: [],
  underCharter: false,
  vesselFeatureId: 'VESSELS:FRA000561631/FJ9112/SM561631',
  vesselId: 1225156,
  vesselIdentifier: VesselIdentifier.INTERNAL_REFERENCE_NUMBER,
  vesselName: 'AD GLORIAM'
}
