env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  describe: readonly
  it: readonly
  expect: readonly
  jest: readonly
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "react-hooks/exhaustive-deps": "off",
  "react/prop-types": "off"
}
settings:
  react:
    version: 16.13.1
