env:
  browser: true
  es6: true

extends:
  - plugin:react/recommended
  - standard

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  describe: readonly
  it: readonly
  expect: readonly
  jest: readonly

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins:
  - react
  - react-hooks

rules:
  no-shadow:
    - warn
    - builtinGlobals: false
      hoist: functions
      allow:
        - done
        - reject
        - resolve
  block-scoped-var: warn
  consistent-return: warn
  no-use-before-define: off
  no-console:
    - warn
    - allow:
        - error
        - warn

  # TODO Re-enable these rules (to error) once refactoring is done
  no-unused-vars: warn

  react/forbid-dom-props: warn
  react/no-access-state-in-setstate: warn
  react/no-array-index-key: warn
  react/prop-types: off
  # No need to enforce this rule since React v17
  react/react-in-jsx-scope:
    off

    # TODO Re-enable these rules (to error) once refactoring is done
  react/forbid-component-props: off
  react/jsx-no-bind: off

  react-hooks/exhaustive-deps: off
  react-hooks/rules-of-hooks: error

settings:
  react:
    version: 16.13.1

overrides:
  - files: "**/*.d.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      ecmaVersion: 2022,
      project: ./tsconfig.json
    rules:
      no-undef: off
      no-unused-vars: off
  - files: "cypress/**/*.js"
    globals:
      beforeEach: true
      context: true
      cy: true
      Cypress: true
