from enum import Enum


class AlertType(Enum):
    THREE_MILES_TRAWLING_ALERT = "THREE_MILES_TRAWLING_ALERT"
    FRENCH_EEZ_FISHING_ALERT = "FRENCH_EEZ_FISHING_ALERT"
    TWELVE_MILES_FISHING_ALERT = "TWELVE_MILES_FISHING_ALERT"
    BOTTOM_GEAR_VME_FISHING_ALERT = "BOTTOM_GEAR_VME_FISHING_ALERT"
    BOTTOM_TRAWL_800_METERS_FISHING_ALERT = "BOTTOM_TRAWL_800_METERS_FISHING_ALERT"
    MISSING_DEP_ALERT = "MISSING_DEP_ALERT"
    MISSING_FAR_ALERT = "MISSING_FAR_ALERT"
    MISSING_FAR_48_HOURS_ALERT = "MISSING_FAR_48_HOURS_ALERT"
    SUSPICION_OF_UNDER_DECLARATION_ALERT = "SUSPICION_OF_UNDER_DECLARATION_ALERT"
    RTC_FISHING_ALERT = "RTC_FISHING_ALERT"
    NEAFC_FISHING_ALERT = "NEAFC_FISHING_ALERT"
    BLI_BYCATCH_MAX_WEIGHT_EXCEEDED_ALERT = "BLI_BYCATCH_MAX_WEIGHT_EXCEEDED_ALERT"
