from enum import Enum


class beaconMalfunctionStage(Enum):
    INITIAL_ENCOUNTER = "INITIAL_ENCOUNTER"
    FOUR_HOUR_REPORT = "FOUR_HOUR_REPORT"
    RELAUNCH_REQUEST = "RELAUNCH_REQUEST"
    TARGETING_VESSEL = "TARGETING_VESSEL"
    CROSS_CHECK = "CROSS_CHECK"
    END_OF_MALFUNCTION = "END_OF_MALFUNCTION"
    ARCHIVED = "ARCHIVED"


class beaconMalfunctionVesselStatus(Enum):
    AT_SEA = "AT_SEA"
    AT_PORT = "AT_PORT"
    NEVER_EMITTED = "NEVER_EMITTED"
    NO_NEWS = "NO_NEWS"
    ACTIVITY_DETECTED = "ACTIVITY_DETECTED"


class endOfMalfunctionReason(Enum):
    RESUMED_TRANSMISSION = "RESUMED_TRANSMISSION"
    TEMPORARY_INTERRUPTION_OF_SUPERVISION = "TEMPORARY_INTERRUPTION_OF_SUPERVISION"
    PERMANENT_INTERRUPTION_OF_SUPERVISION = "PERMANENT_INTERRUPTION_OF_SUPERVISION"


class beaconMalfunctionNotificationType(Enum):
    MALFUNCTION_AT_SEA_INITIAL_NOTIFICATION = "MALFUNCTION_AT_SEA_INITIAL_NOTIFICATION"
    MALFUNCTION_AT_SEA_REMINDER = "MALFUNCTION_AT_SEA_REMINDER"
    MALFUNCTION_AT_PORT_INITIAL_NOTIFICATION = (
        "MALFUNCTION_AT_PORT_INITIAL_NOTIFICATION"
    )
    MALFUNCTION_AT_PORT_REMINDER = "MALFUNCTION_AT_PORT_REMINDER"
    END_OF_MALFUNCTION = "END_OF_MALFUNCTION"
