services:
  db:
    image: ghcr.io/mtes-mct/monitorfish/monitorfish-database:pg16-ts2.14.2-postgis3.4.2
    container_name: monitorfish_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitorfishdb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./infra/dev/database/enable_pg_query_stats_and_history.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./backend/src/main/resources/db/testdata/csv/:/testdata/csv
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30

  flyway:
    image: flyway/flyway
    command: migrate -password=postgres -schemas=public -user=postgres -url=jdbc:postgresql://db:5432/monitorfishdb
    volumes:
      - ../../backend/src/main/resources/db/:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  geoserver:
    image: kartoza/geoserver:2.18.0
    restart: unless-stopped
    ports:
      - 8081:8080
    links:
      - "db:db"
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    depends_on:
      db:
        condition: service_healthy

  geoserver-monitorenv-stubs:
    image: rodolpheche/wiremock
    ports:
      - 8081:8080
    volumes:
      - ./frontend/cypress/mappings/geoserver_monitorenv:/home/wiremock/mappings

  rapportnav-stubs:
    image: rodolpheche/wiremock
    ports:
      - 8082:8080
    volumes:
      - ./frontend/cypress/mappings/rapportnav:/home/wiremock/mappings

  keycloak:
    container_name: monitorfish_keycloak
    image: quay.io/keycloak/keycloak:23.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_PORT=8080
      - KC_HEALTH_ENABLED=true
    ports:
      - "8085:8080"
    volumes:
      - ./infra/dev/keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    healthcheck:
      test: [ "CMD-SHELL",
              "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'" ]
      interval: 30s
      timeout: 5s
      retries: 20

  kafka:
    profiles: [kafka]
    container_name: monitorfish_kafka
    image: confluentinc/cp-kafka:8.1.0
    ports:
      - "9093:9093"
    volumes:
      - ./infra/kafka/certs/kafka/:/etc/kafka/secrets
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SSL:SSL,CONTROLLER:SSL"
      KAFKA_LISTENERS: SSL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.p12
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka-truststore.p12
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.p12
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-truststore.p12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_CREDENTIALS: kafka.keypass
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.keypass
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.keypass
      KAFKA_SSL_CLIENT_AUTH: required

volumes:
  geoserver-data:
    driver: local
  db-data:
    name: db-data-16
