import { REGULATORY_SEARCH_PROPERTIES } from './regulatory'

export const BACKOFFICE_SEARCH_PROPERTIES = [
  REGULATORY_SEARCH_PROPERTIES.TOPIC,
  REGULATORY_SEARCH_PROPERTIES.ZONE,
  REGULATORY_SEARCH_PROPERTIES.REGION,
  REGULATORY_SEARCH_PROPERTIES.SEAFRONT,
  REGULATORY_SEARCH_PROPERTIES.REGULATORY_REFERENCES
]
