export const vesselLabel = {
    VESSEL_NATIONALITY: 'VESSEL_NATIONALITY',
    VESSEL_NAME: 'VESSEL_NAME',
    VESSEL_INTERNAL_REFERENCE_NUMBER: 'VESSEL_INTERNAL_REFERENCE_NUMBER',
    VESSEL_FLEET_SEGMENT: 'VESSEL_FLEET_SEGMENT'
}
