package fr.gouv.cnsp.monitorfish.fakers

import com.neovisionaries.i18n.CountryCode
import fr.gouv.cnsp.monitorfish.domain.entities.vessel.Vessel
import java.util.Date

class VesselFaker {
    companion object {
        fun fakeVessel(
            id: Int = 1,
            internalReferenceNumber: String? = "FAKE_CFR_$id",
            imo: String? = null,
            mmsi: String? = null,
            ircs: String? = null,
            externalReferenceNumber: String? = null,
            vesselName: String? = "FAKE VESSEL $id",
            flagState: CountryCode = CountryCode.FR,
            width: Double? = null,
            length: Double? = null,
            district: String? = null,
            districtCode: String? = null,
            gauge: Double? = null,
            registryPort: String? = null,
            power: Double? = null,
            vesselType: String? = null,
            sailingCategory: String? = null,
            sailingType: String? = null,
            declaredFishingGears: List<String>? = null,
            pinger: Boolean? = null,
            navigationLicenceExpirationDate: Date? = null,
            operatorName: String? = null,
            operatorPhones: List<String>? = null,
            operatorEmail: String? = null,
            proprietorName: String? = null,
            proprietorPhones: List<String>? = null,
            proprietorEmails: List<String>? = null,
            vesselPhones: List<String>? = null,
            vesselEmails: List<String>? = null,
            underCharter: Boolean? = null,
            logbookEquipmentStatus: String? = null,
            logbookSoftware: String? = null,
            hasLogbookEsacapt: Boolean = false,
            hasVisioCaptures: Boolean? = null,
        ): Vessel {
            return Vessel(
                id = id,
                internalReferenceNumber = internalReferenceNumber,
                imo = imo,
                mmsi = mmsi,
                ircs = ircs,
                externalReferenceNumber = externalReferenceNumber,
                vesselName = vesselName,
                flagState = flagState,
                width = width,
                length = length,
                district = district,
                districtCode = districtCode,
                gauge = gauge,
                registryPort = registryPort,
                power = power,
                vesselType = vesselType,
                sailingCategory = sailingCategory,
                sailingType = sailingType,
                declaredFishingGears = declaredFishingGears,
                pinger = pinger,
                navigationLicenceExpirationDate = navigationLicenceExpirationDate,
                operatorName = operatorName,
                operatorPhones = operatorPhones,
                operatorEmail = operatorEmail,
                proprietorName = proprietorName,
                proprietorPhones = proprietorPhones,
                proprietorEmails = proprietorEmails,
                vesselPhones = vesselPhones,
                vesselEmails = vesselEmails,
                underCharter = underCharter,
                logbookEquipmentStatus = logbookEquipmentStatus,
                logbookSoftware = logbookSoftware,
                hasLogbookEsacapt = hasLogbookEsacapt,
                hasVisioCaptures = hasVisioCaptures,
            )
        }
    }
}
