version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: datascience/docs/requirements.txt

sphinx:
  configuration: datascience/docs/source/conf.py