# TODO Rename "dev" to "integration" and "prod" to "production".

name: "Set Version and Environment Profile"
description: "Set ENV_PROFILE, IS_RELEASE & VERSION env vars for the current workflow run."

runs:
  using: "composite"
  steps:
    - name: Is it a Dependabot PR?
      shell: bash
      run: echo ${{ contains(github.ref, 'dependabot') }}

    - name: Get last release version
      id: get-last-release-version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: mtes-mct/monitorfish

    - name: "Set ENV_PROFILE as 'dev' and IS_RELEASE as false by default"
      shell: bash
      run: |
        echo "ENV_PROFILE=dev" >> $GITHUB_ENV
        echo "IS_RELEASE=false" >> $GITHUB_ENV

    - name: "Set IS_RELEASE as true if we are on master branch"
      if: github.ref == 'refs/heads/master'
      shell: bash
      run: echo "IS_RELEASE=true" >> $GITHUB_ENV

    - name: "Set ENV_PROFILE as 'prod' if it's a tag or branch starting with 'v1' or 'v2'"
      if: startsWith(github.ref, 'refs/tags/v1') || startsWith(github.ref, 'refs/heads/v1') || startsWith(github.ref, 'refs/tags/v2') || startsWith(github.ref, 'refs/heads/v2')
      shell: bash
      run: echo "ENV_PROFILE=prod" >> $GITHUB_ENV

    - name: Set version output
      id: set-version
      shell: bash
      run: |
        if [ "${ENV_PROFILE}" != "prod" ]; then
            export VERSION=${{ steps.get-last-release-version.outputs.release }}_snapshot
        else
            export VERSION=${{ steps.get-last-release-version.outputs.release }}
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Print environment profile and version
      shell: bash
      run: |
        echo "ENV_PROFILE: ${{ env.ENV_PROFILE }}"
        echo "IS_RELEASE: ${{ env.IS_RELEASE }}"
        echo "VERSION: ${{ env.VERSION }}"
