SELECT
    id,
    law_type,
    facade,
    layer_name,
    zones,
    region,
    date_fermeture,
    date_ouverture,
    periodes,
    fishing_periods,
    engins,
    engins_interdits,
    mesures_techniques,
    especes,
    species,
    quantites,
    taille,
    especes_interdites,
    autre_reglementation_especes,
    documents_obligatoires,
    autre_reglementation,
    references_reglementaires,
    ST_CurveToLine(geometry) AS geometry,
    geometry_simplified,
    row_hash
FROM prod.reglementation_peche
WHERE id IN :ids