ALTER TABLE reportings ADD COLUMN mmsi VARCHAR;
ALTER TABLE reportings ADD COLUMN imo VARCHAR;
ALTER TABLE reportings ADD COLUMN length DOUBLE PRECISION;
ALTER TABLE reportings ADD COLUMN gear_code VARCHAR;
ALTER TABLE reportings ADD COLUMN is_fishing BOOLEAN;
ALTER TABLE reportings ADD COLUMN last_update_date_utc TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
