CREATE TABLE public.last_positions_vms (
    cfr character varying(100),
    external_immatriculation character varying(100),
    mmsi character varying(100),
    ircs character varying(100),
    vessel_name character varying(100),
    flag_state character varying(100),
    trip_number character varying(100),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    speed double precision,
    course double precision,
    last_position_datetime_utc timestamp without time zone,
    emission_period interval,
    last_logbook_message_datetime_utc timestamp without time zone,
    departure_datetime_utc timestamp without time zone,
    width double precision,
    length double precision,
    registry_port character varying(200),
    district character varying(200),
    district_code character varying(2),
    gear_onboard jsonb,
    segments character varying(50)[],
    species_onboard jsonb,
    total_weight_onboard double precision NOT NULL,
    id integer NOT NULL,
    last_control_datetime_utc timestamp without time zone,
    last_control_infraction boolean,
    post_control_comments text,
    vessel_identifier public.vessel_identifier NOT NULL,
    estimated_current_latitude double precision,
    estimated_current_longitude double precision,
    impact_risk_factor double precision NOT NULL,
    probability_risk_factor double precision NOT NULL,
    detectability_risk_factor double precision NOT NULL,
    risk_factor double precision NOT NULL,
    under_charter boolean,
    is_at_port boolean DEFAULT false NOT NULL,
    alerts character varying(200)[],
    beacon_malfunction_id integer,
    is_manual boolean,
    reportings character varying(200)[],
    vessel_id integer
);
