-- /!\ This file is automatically generated by a local script.
-- Do NOT update it directly, update the associated .jsonc file in /backend/src/main/resources/db/testdata/json/ and execute 'make generate-test-data'.

TRUNCATE TABLE user_layers;

INSERT INTO user_layers (hashed_email, displayed_administrative_layers, displayed_regulatory_zone_ids, selected_regulatory_zone_ids, base_layer) VALUES ('a6ad88a1dcff3355c23693eaf12898065873d38e13f41d8841f05ee2c6a19f3a', '[{"type":"eez_areas","zone":null}]', '["8"]', '["8"]', 'SATELLITE');
