-- /!\ This file is automatically generated by a local script.
-- Do NOT update it directly, update the associated .jsonc file in /backend/src/main/resources/db/testdata/json/ and execute 'make generate-test-data'.

TRUNCATE TABLE silenced_alerts RESTART IDENTITY CASCADE;

INSERT INTO silenced_alerts (id, vessel_name, internal_reference_number, external_reference_number, ircs, vessel_identifier, flag_state, silenced_before_date, value) VALUES (1, 'NATUREL NON FUIR', 'ABC000571489', 'IS726385', 'LRED', 'INTERNAL_REFERENCE_NUMBER', 'FR', NOW() - interval '8 months', '{"seaFront":"MEMN","riskFactor":3.6947,"type":"TWELVE_MILES_FISHING_ALERT","natinfCode":27689}');

INSERT INTO silenced_alerts (id, vessel_name, internal_reference_number, external_reference_number, ircs, vessel_identifier, flag_state, silenced_before_date, value) VALUES (2, 'NATUREL NON FUIR', 'ABC000571489', 'IS726385', 'LRED', 'INTERNAL_REFERENCE_NUMBER', 'FR', NOW() + interval '15 days', '{"seaFront":"MEMN","riskFactor":3.6947,"type":"TWELVE_MILES_FISHING_ALERT","natinfCode":27689}');

INSERT INTO silenced_alerts (id, vessel_name, internal_reference_number, external_reference_number, ircs, vessel_identifier, flag_state, silenced_before_date, value) VALUES (3, 'JARDIN TANT DESCENDRE', 'ABC000417080', 'KS181242', 'QFH9332', 'INTERNAL_REFERENCE_NUMBER', 'FR', NOW() + interval '50 days', '{"seaFront":"NAMO","riskFactor":3.6947,"type":"MISSING_FAR_ALERT","natinfCode":27689}');

INSERT INTO silenced_alerts (id, vessel_name, internal_reference_number, external_reference_number, ircs, vessel_identifier, flag_state, silenced_before_date, value) VALUES (4, 'FRAPPER PREFERER RIRE', 'ABC000900977', 'QG773364', 'CA2048', 'INTERNAL_REFERENCE_NUMBER', 'FR', NOW() + interval '5 hours', '{"seaFront":"SA","riskFactor":3.6947,"type":"THREE_MILES_TRAWLING_ALERT","natinfCode":27689}');

INSERT INTO silenced_alerts (id, vessel_name, internal_reference_number, external_reference_number, ircs, vessel_identifier, flag_state, silenced_before_date, value) VALUES (5, 'FORTUNE ARME ABATTRE', 'ABC000677933', 'IG415546', 'UTIG', 'INTERNAL_REFERENCE_NUMBER', 'X', NOW() + interval '24 hours', '{"seaFront":"NAMO","riskFactor":3.6947,"type":"THREE_MILES_TRAWLING_ALERT","natinfCode":27689}');

SELECT setval('silenced_alerts_id_seq', (SELECT MAX(id) FROM silenced_alerts));