-- /!\ This file is automatically generated by a local script.
-- Do NOT update it directly, update the associated .jsonc file in /backend/src/main/resources/db/testdata/json/ and execute 'make generate-test-data'.

INSERT INTO user_authorizations (hashed_email, is_super_user, service, is_administrator) VALUES ('620726063ea5a8121c70f16f1163c85319ee11f1495e85f63ea107b169864ba0', true, 'Pôle OPS métropole', true);

INSERT INTO user_authorizations (hashed_email, is_super_user, service, is_administrator) VALUES ('a6ad88a1dcff3355c23693eaf12898065873d38e13f41d8841f05ee2c6a19f3a', false, 'Pôle OPS outre-mer', true);
