-- /!\ This file is automatically generated by a local script.
-- Do NOT update it directly, update the associated .jsonc file in /backend/src/main/resources/db/testdata/json/.

INSERT INTO prior_notification_checks (report_id, is_in_verification_scope, is_verified, is_pending_send, is_sent, created_at, updated_at) VALUES ('FAKE_OPERATION_101', false, false, false, false, NOW() AT TIME ZONE 'UTC' - INTERVAL '5 minutes', NOW() AT TIME ZONE 'UTC' - INTERVAL '5 minutes');

INSERT INTO prior_notification_checks (report_id, is_in_verification_scope, is_verified, is_pending_send, is_sent, created_at, updated_at) VALUES ('00000000-0000-4000-0000-000000000001', true, false, false, false, NOW() AT TIME ZONE 'UTC' - INTERVAL '5 minutes', NOW() AT TIME ZONE 'UTC' - INTERVAL '5 minutes');
