-- /!\ This file is automatically generated by a local script.
-- Do NOT update it directly, update the associated .jsonc file in /backend/src/main/resources/db/testdata/json/ and execute 'make generate-test-data'.

TRUNCATE TABLE favorite_vessels;

INSERT INTO favorite_vessels (hashed_email, vessels) VALUES ('620726063ea5a8121c70f16f1163c85319ee11f1495e85f63ea107b169864ba0', '[{"vesselId":1,"cfr":"FAK000999999","ircs":"CALLME","externalIdentification":"DONTSINK","name":"PHENOMENE","flagState":"FR","vesselIdentifier":"INTERNAL_REFERENCE_NUMBER"},{"vesselId":2,"cfr":"U_W0NTFINDME","ircs":"QGDF","externalIdentification":"TALK2ME","name":"MALOTRU","flagState":"UNDEFINED","vesselIdentifier":"INTERNAL_REFERENCE_NUMBER"}]');

INSERT INTO favorite_vessels (hashed_email, vessels) VALUES ('a6ad88a1dcff3355c23693eaf12898065873d38e13f41d8841f05ee2c6a19f3a', '[{"vesselId":3,"cfr":"FR263418260","ircs":"IR12A","externalIdentification":"08FR65324","name":"LE b@TO","flagState":"FR","vesselIdentifier":"INTERNAL_REFERENCE_NUMBER"}]');
