-- /!\ This file is automatically generated by a local script.
-- Do NOT update it directly, update the associated .jsonc file in /backend/src/main/resources/db/testdata/json/ and execute 'make generate-test-data'.

DELETE FROM infractions;

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (17, 'Reg pêche 3', 'Pêche', 'Infraction 4');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (1000, 'Reg pêche 1', 'Sécurité / Rôle', 'Infraction 6');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (1030, 'Reg pêche 1', 'Pêche', 'Infraction 5');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (1508, 'ART.L.8224-1, ART.L.8221-1 AL.1 1°, ART.L.8221-3, ART.L.8221-4, ART.L.8221-5, ART.L.8221-6 C.TRAVAIL.', 'Pêche', 'EXECUTION D''UN TRAVAIL DISSIMULE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (1509, 'ART.L.8224-1, ART.L.8221-1 AL.1 3°, ART.L.8221-3, ART.L.8221-4, ART.L.8221-5 C.TRAVAIL.', 'Pêche', 'RECOURS AUX SERVICES D''UNE PERSONNE EXERCANT UN TRAVAIL DISSIMULE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2000, 'Reg pêche 2', 'Sécurité / Rôle', 'Infraction 7');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2584, 'ART.L.945-1 2°, ART.L.943-1, ART.L.943-7, ART.L.943-8 AL.3 C.RURAL. ART.3 §1 H) REGLT.CE DU 29/09/2008.', 'Pêche', 'OBSTACLE A UNE SAISIE EN MATIERE DE PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2593, 'ART.L.945-4 §I 8°, ART.R.922-6, ART.D.922-16 C.RURAL. ART.3 §1 E) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME AVEC UN ENGIN DONT L''USAGE EST INTERDIT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2596, 'ART.L.945-4 §I 3°, ART.L.921-1, ART.R.922-6 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME DANS UNE ZONE INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2600, 'ART.L.945-4 §I 18° C.RURAL.', 'Pêche', 'IMMERSION D''ORGANISMES MARINS DANS DES CONDITIONS IRREGULIERES - PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2603, 'ART.L.945-4 §I 19°, ART.L.923-1, ART.R.923-9, ART.R.923-10, ART.R.923-11 C.RURAL.', 'Pêche', 'FORMATION OU IMMERSION NON AUTORISEE D''EXPLOITATION AQUACOLE OU DE STRUCTURE DE CULTURE OU DE CAPTURE MARINE - PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2604, 'ART.L.945-2 §I 5°, ART.L.941-4, ART.L.942-5 C.RURAL. ART.3 §1 H) REGLT.CE DU 29/09/2008.', 'Pêche', 'REFUS, PAR LE CAPITAINE D''UN NAVIRE DE PECHE MARITIME D''OBTEMPERER A UNE SOMMATION DE STOPPER POUR SE SOUSTRAIRE A UN CONTROLE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2605, 'ART.L.945-3 3°, ART.L.941-1, ART.L.942-1 C.RURAL.', 'Pêche', 'ENTRAVE AU CONTROLE D''EXPLOITATION AQUACOLE, DE CULTURE MARINE OU D''ETABLISSEMENT DE CAPTURE OU DE STRUCTURE ARTIFICIELLE - PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2606, 'ART.L.945-3 1°, ART.L.941-1, ART.L.942-1 C.RURAL. ART.3 §1 H) REGLT.CE DU 29/09/2008.', 'Pêche', 'ENTRAVE AU CONTROLE OU A LA VISITE DE NAVIRE OU ENGIN FLOTTANT - PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2608, 'd1852', 'Pêche', 'Peche maritime non autorisee dans les eaux maritimes ou salees francaises par un navire de pays tiers a l''union europeenne');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2609, 'ART.L.945-2 §I 3°, ART.L.921-9 C.RURAL.', 'Pêche', 'PECHE MARITIME NON CONFORME A L''AUTORISATION, DANS LES EAUX MARITIMES OU SALEES FRANCAISES PAR UN NAVIRE DE PAYS TIERS A L''UNION EUROPEENNE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (2610, 'ART.L.945-2 §I 4° C.RURAL. ART.17 REGLT.CE 2002-2371 DU 20/12/2002.', 'Pêche', 'PECHE MARITIME NON AUTORISEE DANS LES EAUX SOUS SOUVERAINETE OU JURIDICTION FRANCAISES PAR CAPITAINE DE NAVIRE COMMUNAUTAIRE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (3000, 'Reg pêche 2', 'Environnement', 'Infraction 8');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (4000, 'Reg pêche 9', 'Environnement', 'Infraction 9');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (4234, 'ART.413-BIS 3°, ART.71 C.DOUANES.', 'Sécurité / Rôle', 'NON PRESENTATION PAR UN CAPITAINE DE SON JOURNAL DE BORD AU VISA DES AGENTS DES DOUANES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (4485, 'ART.L.5523-2, ART.L.5523-3 C.TRANSPORTS.', 'Pêche', 'EXERCICE IRREGULIER D''UN COMMANDEMENT OU D''UNE AUTRE FONCTION A BORD D''UN NAVIRE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (4761, 'ART.L.5241-12 AL.1, AL.2, ART.L.5241-3, ART.L.5241-4, ART.L.5241-1 §I C.TRANSPORTS. ART.3 §I, ART.8-1, ART.9, ART.10 DECRET 84-810 DU 30/08/1984.', 'Pêche', 'EXPLOITATION OU COMMANDEMENT DE NAVIRE SANS TITRE DE SECURITE OU CERTIFICAT DE PREVENTION DE LA POLLUTION EN COURS DE VALIDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7057, 'ART.L.945-4 §I 9° C.RURAL.', 'Pêche', 'DETENTION D''UN ENGIN DE PECHE MARITIME DONT L''USAGE EST INTERDIT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7059, 'd1852', 'Pêche', 'Peche maritime avec un engin dans une zone ou son emploi est interdit');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7060, 'ART.L.945-4 §I 10°, ART.R.922-6 C.RURAL. ART.3 §1 E) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME AVEC UN ENGIN PENDANT UNE PERIODE OU SON EMPLOI EST INTERDIT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7061, 'ART.L.945-4 §I 3°, ART.L.921-1, ART.R.922-6 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME D''UNE ESPECE DANS UNE ZONE OU SA PECHE EST INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7062, 'ART.L.945-4 §I 3°, ART.L.921-1, ART.L.922-2, ART.R.922-6 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME D''UNE ESPECE A UNE PERIODE OU SA PECHE EST INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7063, 'ART.L.945-4 §I 15°, ART.R.922-6 C.RURAL. ART.3 §1 D) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE DONT LA PECHE EST INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7064, 'ART.L.945-4 §I 15°, ART.D.932-1 C.RURAL. ART.3 §1 D) REGLT.CE DU 29/09/2008.', 'Pêche', 'TRANSBORDEMENT, DEBARQUEMENT OU TRANSPORT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE DONT LA PECHE EST INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7983, 'ART.L.945-4 §I 15°, ART.D.922-1 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE DE TAILLE, CALIBRE OU POIDS PROHIBE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (7984, 'ART.L.945-4 §I 15°, ART.D.922-1 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'TRANSBORDEMENT, DEBARQUEMENT OU TRANSPORT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE DE TAILLE, CALIBRE OU POIDS PROHIBE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (10400, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-2 AL.2 C.RURAL.', 'Pêche', 'DEBARQUEMENT DE PRODUITS DE PECHE MARITIME ET D''AQUACULTURE MARINE EN DEHORS DES LIEUX DETERMINES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12891, 'ART.L.945-4 §I 8° C.RURAL. ART.3 §1 E) REGLT.CE DU 29/09/2008.', 'Pêche', 'PRATIQUE DE LA PECHE MARITIME AVEC UN MODE DE PECHE INTERDIT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12898, 'ART.L.945-4 §I 10°, ART.R.922-6 C.RURAL. ART.3 §1 E) REGLT.CE DU 29/09/2008.', 'Pêche', 'UTILISATION POUR LA PECHE MARITIME D''INSTRUMENT OU APPAREIL DANS UNE ZONE OU SON EMPLOI EST INTERDIT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12900, 'ART.L.945-4 §I 15° C.RURAL.', 'Pêche', 'PECHE DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE EN QUANTITE OU EN POIDS SUPERIEURS A CEUX AUTORISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12902, 'ART.L.945-4 §I 15° C.RURAL.', 'Pêche', 'TRANSBORDEMENT, DEBARQUEMENT OU TRANSPORT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE EN QUANTITE OU POIDS SUPERIEURS A CEUX AUTORISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12912, 'ART.L.945-4 §I 1°, ART.L.921-7, ART.R.921-9, ART.R.921-14 C.RURAL.', 'Pêche', 'PECHE MARITIME SANS PERMIS DE MISE EN EXPLOITATION DE NAVIRE DE PECHE PROFESSIONNELLE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12918, 'ART.L.945-4 §I 6°, ART.D.922-15 C.RURAL. ART.3 §I E) REGLT.CE DU 29/09/2008.', 'Pêche', 'UTILISATION POUR LA PECHE MARITIME D''UN NOMBRE D''ENGINS OU APPAREILS EN NOMBRE SUPERIEUR A CELUI AUTORISE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (12922, 'ART.L.945-2 §I 1° C.RURAL. ART.1, ART.6 REGLT.EX.UE DU 08/04/2011. ART.3 §1 F) REGLT.CE DU 29/09/2008.', 'Pêche', 'DISSIMULATION OU FALSIFICATION PAR CAPITAINE D''ELEMENT D''IDENTIFICATION DE NAVIRE DE PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22035, 'ART.L.1521-9, ART.L.1521-3, ART.L.1521-4, ART.L.1521-5 C.DEFENSE.', 'Pêche', 'REFUS D''OBTEMPERER AUX INJONCTIONS D''UN COMMANDANT LORS DU CONTROLE EN MER D''UN NAVIRE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22070, 'ART.L.945-4 §I 1°,ART.L.921-1, ART.R.921-15, ART.R.921-18, ART.R.921-20, ART.R.921-29, ART.R.921-30 C.RURAL. ART.3 §1 A) REGLT.CE DU 29/09/2008. ART.6, ART.7 REGLT.CE DU 20/11/2009.', 'Pêche', 'PECHE MARITIME SANS AUTORISATION');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22182, 'ART.57 §I 1°, ART.4 §II DECRET 84-810 DU 30/08/1984. ART.L.5241-1 §I C.TRANSPORTS.', 'Sécurité / Rôle', 'EXPLOITATION OU COMMANDEMENT D''UN NAVIRE SANS RESPECTER LES CONDITIONS PARTICULIERES PORTEES SUR LE PERMIS DE NAVIGATION');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22205, 'ART.57 §I 2°, ART.53 §I 1°, ART.4 §I DECRET 84-810 DU 30/08/1984.', 'Sécurité / Rôle', 'NAVIGATION MARITIME SANS PRESENCE A BORD DU PERMIS DE NAVIGATION OU DU DOCUMENT EN TENANT LIEU');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22206, 'Reg pêche 1', 'Pêche', 'Infraction 1');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22222, 'Reg pêche 2', 'Pêche', 'Infraction 3');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22806, 'ART.L.958-8 1°, ART.L.958-5, ART.R.958-5, ART.R.958-7, ART.R.958-8 C.RURAL.', 'Pêche', 'PECHE, CHASSE AUX ANIMAUX MARINS SANS AUTORISATION DANS LES TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22807, 'ART.L.958-8 3°, ART.L.958-7, ART.R.958-2 C.RURAL. ART.11 ORD 2016-1687 DU 08/12/2016.', 'Pêche', 'PENETRATION D''UN NAVIRE DE PECHE MARITIME OU DE TRANSPORT DE POISSON DANS LA ZONE ECONOMIQUE DES TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES SANS SIGNALER SON ENTREE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (22808, 'ART.L.958-8 3°, ART.L.958-7, ART.R.958-2 C.RURAL. ART.11 ORD 2016-1687 DU 08/12/2016.', 'Pêche', 'PENETRATION D''UN NAVIRE DE PECHE MARITIME OU DE TRANSPORT DE POISSON DANS LA ZONE ECONOMIQUE DES TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES SANS DECLARER LE TONNAGE DE POISSON DETENU A BORD');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (23581, 'Arreté du 12/01/3021', 'Pêche', 'Taille de maille non réglementaire');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (23584, 'Arreté du 18/01/3021', 'Sécurité / Rôle', 'Défaut AIS');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (23588, 'Arreté du 15/01/3021', 'Pêche', 'Chalutage dans la zone des 3 milles');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27679, 'ART.L.958-8 2°, ART.L.958-5, ART.R.958-5, ART.R.958-7, ART.R.958-8 C.RURAL.', 'Pêche', 'EXPLOITATION DE PRODUITS DE LA MER PECHES SANS AUTORISATION DANS LES TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27685, 'ART.L.945-3 2°, ART.L.941-1, ART.L.942-1 C.RURAL. ART.3 §1 H) REGLT.CE DU 29/09/2008.', 'Pêche', 'DISSIMULATION, AUX AGENTS CHARGES DE LA POLICE DE LA PECHE, DE CAPTURES, ENGINS OU DOCUMENTS DETENUS A BORD D''UN NAVIRE DE PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27686, 'ART.L.945-4 §I 3°, ART.L.921-1 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME A UNE PROFONDEUR INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27687, 'ART.L.945-4 §I 3°, ART.L.921-1 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME D''UNE ESPECE A UNE PROFONDEUR OU SA PECHE EST INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27688, 'ART.L.945-4 §I 13°, ART.R.913-1 C.RURAL. ART.9, ART.10, ART.11 REGLT.CE DU 20/11/2009. ART.3 §1 B) REGLT.CE DU 29/09/2008.', 'Pêche', 'NON RESPECT DES OBLIGATIONS D''ENREGISTREMENT ET DE COMMUNICATION DES DONNEES REQUISES DANS LE CADRE DU SYSTEME DE SURVEILLANCE DES NAVIRES DE PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27689, 'ART.L.945-2 §I 3°, ART.L.921-9 C.RURAL.	Pêche', 'Pêche', 'Pêche	Non respect des obligations d''enregistrement et de communication des donnees requises dans le cadre du systeme de declaration par voie electronique - peche maritime');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27693, 'ART.L.945-4 §I 17° C.RURAL. ART.L.5231-1, ART.L.5231-2 C.TRANSPORTS.', 'Pêche', 'DETENTION DE PRODUITS DE LA PECHE MARITIME A BORD D''UN NAVIRE OU EMBARCATION NON TITULAIRE D''UN PERMIS D''ARMEMENT A LA PECHE OU AUX CULTURES MARINES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27695, 'ART.L.958-8 4°, ART.L.958-5, ART.R.958-5, ART.R.958-11, ART.R.922-6 C.RURAL.', 'Pêche', 'PECHE MARITIME DANS UNE ZONE INTERDITE DES TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27696, 'ART.L.958-8 4°, ART.L.958-5, ART.R.958-5, ART.R.958-11, ART.R.922-6 C.RURAL.', 'Pêche', 'PECHE MARITIME A UNE EPOQUE INTERDITE DANS LES TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27698, 'ART.L.958-9 C.RURAL.', 'Pêche', 'DETENTION NON AUTORISEE, A BORD D''UN NAVIRE DE PECHE MARITIME, D''EXPLOSIF OU DE SUBSTANCE DANGEREUSES POUR LES ESPECES ANIMALES - TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27699, 'ART.L.958-10 C.RURAL.', 'Pêche', 'UTILISATION POUR LA PECHE MARITIME DE MATIERE EXPLOSIVE OU DE SUBSTANCE DANGEREUSE POUR LES ESPECES ANIMALES - TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27701, 'ART.L.958-11, ART.L.958-10 C.RURAL.', 'Pêche', 'VENTE, MISE EN VENTE DE PRODUITS DE PECHE MARITIME EFFECTUEE AVEC DES MATIERES EXPLOSIVES OU DES SUBSTANCES DANGEREUSES POUR LES ESPECES ANIMALES - TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27702, 'ART.L.958-11, ART.L.958-10 C.RURAL.', 'Pêche', 'TRANSPORT DE PRODUITS DE PECHE MARITIME EFFECTUEE AVEC DES MATIERES EXPLOSIVES OU DES SUBSTANCES DANGEREUSES POUR LES ESPECES ANIMALES - TERRES AUSTRALES ET ANTARCTIQUES FRANCAISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27712, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-3 C.RURAL. ART.17, ART.18 REGLT.CE DU 20/11/2009. ART.6 REGLT.CE DU 29/09/2008.', 'Pêche', 'DEBARQUEMENT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE SANS NOTIFICATION PREALABLE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27714, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-3 C.RURAL.', 'Pêche', 'TRANSBORDEMENT SANS AUTORISATION DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27715, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-3 C.RURAL.', 'Pêche', 'DEBARQUEMENT SANS AUTORISATION DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27717, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-2 AL.1 C.RURAL. ART.5 §1 REGLT.CE DU 29/09/2008. ART.20 §1 REGLT.CE DU 20/11/2009.', 'Pêche', 'TRANSBORDEMENT HORS D''UN PORT DESIGNE DE PRODUITS DE LA PECHE MARITIME OU DE L''AQUACULTURE MARINE D''ESPECES SOUMISES A UN PLAN PLURIANNUEL');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27718, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-2 AL.1 C.RURAL. ART.43 §1, §2 REGLT.CE DU 20/11/2009.', 'Pêche', 'DEBARQUEMENT HORS D''UN PORT DESIGNE DE PRODUITS DE LA PECHE MARITIME OU DE L''AQUACULTURE MARINE D''ESPECES SOUMISES A UN PLAN PLURIANNUEL');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27721, 'ART.L.945-4 §I 5°, ART.L.932-1, ART.R.932-2 AL.3 C.RURAL.', 'Pêche', 'DEBARQUEMENT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE HORS DES HORAIRES AUTORISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27724, 'Art. 128.5.12.d', 'Pêche', 'Utilisation d''engin de pêche maritime non conforme aux mesures techniques de conservation et de gestion des ressources');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27725, 'ART.L.945-4 §I 10° C.RURAL. ART.3 §1 E) REGLT.CE DU 29/09/2008.', 'Pêche', 'DETENTION D''ENGIN DE PECHE MARITIME NON CONFORME AUX MESURES TECHNIQUES DE CONSERVATION ET DE GESTION DES RESSOURCES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27726, 'ART.L.945-4 §I 15°, ART.R.932-5 C.RURAL.', 'Pêche', 'PECHE MARITIME SANS TRI DES CAPTURES AU DEBARQUEMENT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27727, 'ART.L.945-4 §I 15°, ART.R.932-4, ART.R.932-6 C.RURAL. ART.60 REGLT.CE DU 20/11/2009. ART.71, ART.72 REGLT.EX.UE DU 08/04/2011.', 'Pêche', 'NON RESPECT DE L''OBLIGATION DE PESER LES PRODUITS DE LA PECHE MARITIME SUR UN SYSTEME AGREE AVANT LEUR PREMIERE MISE SUR LE MARCHE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27728, 'ART.L.945-4 §I 15°, ART.D.922-12 C.RURAL.', 'Pêche', 'PECHE MARITIME D''ESPECE DETERMINEE SANS REJET IMMEDIAT DES CAPTURES ACCESSOIRES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27729, 'ART.L.945-4 15°, ART.R.932-4, ART.R.932-7 C.RURAL. ART.58 REGLT.CE DU 20/11/2009. ART.67, ART.68 REGLT.EX.UE DU 08/04/2011.', 'Pêche', 'PECHE MARITIME SANS MARQUAGE CONFORME DES CAPTURES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27730, 'ART.L.945-4 §I 15°, ART.R.922-25 C.RURAL.', 'Pêche', 'MUTILATION, PREPARATION OU TRANSFORMATION INTERDITE D''ESPECES MARITIMES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27731, 'ART.L.945-4 §I 6° C.RURAL. ART.3 §1 E) REGLT.CE DU 29/09/2008.', 'Pêche', 'DETENTION A BORD D''UN NAVIRE D''ENGIN, DISPOSITIF, INSTRUMENT OU APPAREIL PROHIBE POUR LA PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27748, 'ART.L.945-4 §I 16° C.RURAL. ART.15 §1,§5 REGLT.UE DU 11/12/2013.', 'Pêche', 'NON RESPECT DE L''OBLIGATION DE DEBARQUEMENT D''ESPECES CAPTUREES LORS D''OPERATION DE PECHE MARITIME');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27879, 'ART.L.945-2 §II A),B) C.RURAL. ART.3 §1 L) REGLT.CE DU 29/09/2008.', 'Pêche', 'EXPLOITATION, GESTION OU POSSESSION D''UN NAVIRE DE PECHE MARITIME NON IMMATRICULE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27885, 'ART.L.945-4 §I 12°, ART.L.932-2, ART.R.913-1 C.RURAL. ART.3 §1 B) REGLT.CE DU 29/09/2008. ART.4 §1 REGLT.CE DU 20/11/2009.', 'Pêche', 'EXERCICE D''ACTIVITE DE PECHE MARITIME SANS RESPECT DES OBLIGATIONS DECLARATIVES NECESSAIRES AU CONTROLE DES ACTIVITES DE PECHES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27898, 'ART.L.945-4 §I 14°,1°,3°,8°,10°,12°,13° C.RURAL. ART.4 §1 REGLT.CE DU 20/11/2009.', 'Pêche', 'TRANSPORT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE PROVENANT D''UNE ACTIVITE DE PECHE ILLEGALE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (27900, 'ART.L.945-4 §I 14°,5° C.RURAL.', 'Pêche', 'MISE EN VENTE, VENTE, STOCKAGE OU EXPOSITION DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE DEBARQUES OU TRANSBORDES ILLEGALEMENT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (28346, 'ART.L.945-4 15° C.RURAL', 'Pêche', 'Détention de produits de la pêche maritime et de l''aquaculture marine de taille, calibre ou poids prohibe');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (28347, 'ART.L.945-4 §I 15° C.RURAL. ART.3 §1 D) REGLT.CE DU 29/09/2008.', 'Pêche', 'DETENTION DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE DONT LA PECHE EST INTERDITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (28348, 'ART.L.945-4 §I 15° C.RURAL.', 'Pêche', 'DETENTION A BORD D''UN NAVIRE DE PECHE DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE EN QUANTITE OU EN POIDS SUPERIEURS A CEUX AUTORISES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (30028, 'ART.L.5523-5 AL.1, ART.L.5522-2 §II C.TRANSPORTS.', 'Pêche', 'NAVIGATION AVEC UN EQUIPAGE SANS ETRE MUNI DE LA FICHE D''EFFECTIF MINIMAL');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (30029, 'ART.L.5523-5 AL.1, ART.L.5522-2 §I C.TRANSPORTS. ART.1, ART.2 DECRET 2017-187 DU 14/02/2017.', 'Pêche', 'NAVIGATION AVEC UN EQUIPAGE INSUFFISANT EN NOMBRE ET QUALIFICATION POUR GARANTIR LA SECURITE ET LA SURETE DE LA NAVIGATION');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (30032, 'ART.L.5523-6 1°, ART.L.5521-1, ART.L.5521-1-1, ART.L.5511-3, ART.R.5521-7, ART.R.5521-8, ART.R.5521-9 C.TRANSPORTS.', 'Pêche', 'ADMISSION A BORD D''UN NAVIRE D''UN MEMBRE D''EQUIPAGE NE DISPOSANT PAS DE CERTIFICAT D''APTITUDE MEDICALE VALIDE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (30034, 'ART.L.5523-6 3°, ART.L.5521-2, ART.L.5511-3 C.TRANSPORTS.', 'Pêche', 'ADMISSION A BORD D''UN NAVIRE D''UN MEMBRE D''EQUIPAGE SANS TITRE DE FORMATION CORRESPONDANT A SES FONCTIONS');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (30792, 'ART.R.945-3 1°, ART.R.921-68 C.RURAL.', 'Sécurité / Rôle', 'PRATIQUE DE LA PECHE A PIED MARITIME PROFESSIONNELLE SANS PERMIS DE PECHE VALIDE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (30835, 'ART.L.945-4 §I 15°, ART.L.922-2 C.RURAL. ART.44 REGLT.CE DU 20/11/2009.', 'Pêche', 'CONSERVATION, A BORD D''UN NAVIRE DE PECHE, DE CAPTURES DE STOCKS DEMERSAUX FAISANT L''OBJET D''UN PLAN PLURIANNUEL SANS PLAN D''ARRIMAGE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (31004, 'ART.L.945-4 §I 12°, ART.L.932-2, ART.R.913-1 C.RURAL. ART.68 REGLT.CE DU 20/11/2009.', 'Pêche', 'TRANSPORT DE PRODUITS DE LA PECHE MARITIME SANS DOCUMENT DE TRANSPORT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (31116, 'ART.7, ART.3 DECRET 2015-598 DU 02/06/2015. ART.L.5521-3 §I C.TRANSPORTS.', 'Contravention de 4ème classe', 'ADMISSION A BORD D''UN NAVIRE BATTANT PAVILLON FRANCAIS D''UN CAPITAINE NE JUSTIFIANT PAS DU NIVEAU DE CONNAISSANCE DE LA LANGUE FRANCAISE ET DES MATIERES JURIDIQUES');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (31122, 'ART.9 1°, ART.8 DECRET 2015-406 DU 10/04/2015. ART.L.5522-3 C.TRANSPORTS.', 'Sécurité / Rôle', 'NON MISE A DISPOSITION DES AUTORITES DE LA LISTE D''EQUIPAGE D''UN NAVIRE BATTANT PAVILLON FRANCAIS');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (31123, 'ART.9 2°, ART.1, ART.2, ART.3, ART.5 DECRET 2015-406 DU 10/04/2015. ART.L.5522-3 C.TRANSPORTS.', 'Sécurité / Rôle', 'TENUE NON CONFORME DE LA LISTE D''EQUIPAGE D''UN NAVIRE BATTANT PAVILLON FRANCAIS');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (32071, 'ART.L.945-4 §II, §I 3°, ART.L.921-1, ART.R.922-6 C.RURAL. ART.3 §1 C) REGLT.CE DU 29/09/2008.', 'Pêche', 'PECHE MARITIME D''ANGUILLE EUROPEENNE, D''ESTURGEON EUROPEEN OU DE SAUMON ATLANTIQUE DANS UNE ZONE INTERDITE - ESPECE PROTEGEE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (32099, 'ART.L.945-4 §II, §I 1°, ART.L.921-1 C.RURAL. ART.3 §1 A) REGLT.CE 29/09/2008. ART.6, ART.7 REGLT.CE DU 20/11/2009.', 'Pêche', 'PECHE MARITIME D''ANGUILLE EUROPEENNE, D''ESTURGEON EUROPEEN OU DE SAUMON ATLANTIQUE SANS LICENCE OU AUTORISATION - ESPECE PROTEGEE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (32326, 'ART.R.5232-25 1°, ART.L.5232-1, ART.L.5231-1, ART.L.5231-2 1°, ART.R.5232-1-1, ART.D.5232-3 C.TRANSPORTS.', 'Sécurité / Rôle', 'NAVIGATION PROFESSIONNELLE SANS PERMIS D''ARMEMENT');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (32327, 'ART.R.5232-25 2°, ART.D.5232-3, ART.L.5232-1 C.TRANSPORTS.', 'Sécurité / Rôle', 'NON PRESENTATION DU PERMIS D''ARMEMENT D''UN NAVIRE A USAGE PROFESSIONNEL');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (33914, 'ART.L.945-4 §I 15°, ART.R.932-4, ART.R.932-7 C.RURAL. ART.58 REGLT.CE DU 20/11/2009. ART.67, ART.68 REGLT.EX.UE DU 08/04/2011.', 'Pêche', 'TRANSBORDEMENT, DEBARQUEMENT OU TRANSPORT DE PRODUITS DE LA PECHE MARITIME ET DE L''AQUACULTURE MARINE SANS MARQUAGE CONFORME DE TRACABILITE');

INSERT INTO infractions (natinf_code, regulation, infraction_category, infraction) VALUES (34314, 'ART.L.945-4 §I 15° C.RURAL. ART.15 §12 REGLT.UE DU 11/12/2013.', 'Pêche', 'NON RESPECT DE L''OBLIGATION DE REJET DE PRODUITS DE LA PECHE MARITIME NON CONFORMES');
