CREATE TABLE public.reglementation_peche
(
    id                        bigint NOT NULL,
    autorisations             text,
    captures_accessoires      text,
    crocs                     text,
    date_fermeture            timestamp without time zone,
    date_fermeture2           text,
    date_ouverture            timestamp without time zone,
    date_ouverture2           text,
    dates                     text,
    documents_obligatoires    text,
    drague_a_main             text,
    engins                    text,
    engins_interdits          text,
    especes                   text,
    especes_interdites        text,
    etat                      text,
    filets_encerclants        text,
    filets_fixes              text,
    filets_maillants_tremails text,
    geometry                  public.geometry(Geometry, 4326),
    geometry_type             text,
    gisement                  text,
    interdictions             text,
    layer_name                text,
    mesures_techniques        text,
    nasses                    text,
    obligations               text,
    palangres                 text,
    peche_sous_marins         text,
    periodes                  text,
    petite_drague_coquillage  text,
    ports                     text,
    prises_accessoires        text,
    quantites                 text,
    references_reglementaires text,
    rejets                    text,
    senne_de_plage            text,
    senne_tournante           text,
    suivi_sanitaire           text,
    taille                    text,
    type                      text,
    valeur                    double precision,
    zones                     text,
    facade                    text,
    region                    text,
    interdits                 text
);

ALTER TABLE ONLY public.reglementation_peche
    ADD CONSTRAINT reglementation_peche_pkey PRIMARY KEY (id);

CREATE INDEX idx_reglementation_peche_geometry ON public.reglementation_peche USING gist (geometry);
