DROP TABLE IF EXISTS eez_areas;

CREATE TABLE eez_areas (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon,4326),
    fid bigint,
    "MRGID" bigint,
    "GEONAME" character varying(100),
    "MRGID_TER1" bigint,
    "POL_TYPE" character varying(80),
    "MRGID_SOV1" bigint,
    "TERRITORY1" character varying(80),
    "ISO_TER1" character varying(80),
    "SOVEREIGN1" character varying(80),
    "MRGID_TER2" bigint,
    "MRGID_SOV2" bigint,
    "TERRITORY2" character varying(80),
    "ISO_TER2" character varying(80),
    "SOVEREIGN2" character varying(80),
    "MRGID_TER3" bigint,
    "MRGID_SOV3" bigint,
    "TERRITORY3" character varying(80),
    "ISO_TER3" character varying(80),
    "SOVEREIGN3" character varying(80),
    "X_1" double precision,
    "Y_1" double precision,
    "MRGID_EEZ" bigint,
    "AREA_KM2" bigint,
    "ISO_SOV1" character varying(80),
    "ISO_SOV2" character varying(80),
    "ISO_SOV3" character varying(80),
    "UN_SOV1" bigint,
    "UN_SOV2" bigint,
    "UN_SOV3" bigint,
    "UN_TER1" bigint,
    "UN_TER2" bigint,
    "UN_TER3" bigint
);

CREATE INDEX ON public.eez_areas USING GIST (geom);
