CREATE TABLE if not exists public.all_decisions (
    autorisations text,
    captures_accessoires text,
    crocs text,
    date_fermeture text,
    date_ouverture text,
    documents_obligatoires text,
    drague_a_main text,
    engins text,
    engins_interdits text,
    especes text,
    especes_interdites text,
    etat text,
    filets_encerclants text,
    filets_fixes text,
    filets_maillants_tremails text,
    geometry public.geometry(Geometry,4326),
    geometry_type text,
    gisement text,
    interdictions text,
    jours text,
    layer_name text,
    mesures_techniques text,
    nasses text,
    obligations text,
    palangres text,
    peche_sous_marins text,
    periodes text,
    petite_drague_coquillage text,
    ports text,
    prises_accessoires text,
    quantites text,
    references_reglementaires text,
    rejets text,
    senne_de_plage text,
    senne_tournante text,
    suivi_sanitaire text,
    taille text,
    type text,
    zones text
);

CREATE INDEX IF NOT EXISTS idx_all_decisions_geometry ON public.all_decisions USING gist (geometry);
