export enum vesselLabel {
  VESSEL_FLEET_SEGMENT = 'VESSEL_FLEET_SEGMENT',
  VESSEL_INTERNAL_REFERENCE_NUMBER = 'VESSEL_INTERNAL_REFERENCE_NUMBER',
  VESSEL_NAME = 'VESSEL_NAME',
  VESSEL_NATIONALITY = 'VESSEL_NATIONALITY'
}
