package fr.gouv.cnsp.monitorfish.infrastructure.database.repositories.interfaces

import fr.gouv.cnsp.monitorfish.infrastructure.database.entities.ProducerOrganizationMembershipEntity
import org.springframework.data.repository.CrudRepository

interface DBProducerOrganizationMembership : CrudRepository<ProducerOrganizationMembershipEntity, String>
